name: CI/CD Full Stack

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 — Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3 — Build frontend
      - name: Build frontend
        working-directory: client
        run: |
          npm install
          npm run build

      # Step 4 — Install backend dependencies
      - name: Install backend dependencies
        working-directory: server
        run: npm install

      # Step 5 — Deploy backend to Render
      - name: Deploy backend (Render)
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json"

      # Step 6 — Deploy frontend to Vercel
      - name: Deploy frontend (Vercel)
        uses: amondnet/vercel-action@v25
        with:
            vercel-token: NlFP5qUAglnOhBoDrgZE9dPh
            vercel-org-id: team_8YT4N8bdmljtIq5mV35rfKEg
            vercel-project-id: prj_PWabRiGi1km4IMcKeCJKXxgtBtlT
            working-directory: client
            scope: team_8YT4N8bdmljtIq5mV35rfKEg
            vercel-args: '--prod --scope team_8YT4N8bdmljtIq5mV35rfKEg'
