name: Python Setup

on:
  pull_request:

jobs:
  install-python:
    runs-on: self-hosted

    steps:
    - name: Update Ubuntu Packages
      run: |
        sudo apt update

    - name: Install Python
      run: sudo apt install -y python3
